<?php $catalogSearchHelper =  $this->helper('catalogsearch');?>
<?php
//ng-submit="(searchForm.$valid && (searchCtrl.q!='')) && searchCtrl.search('')"
?>
<form ng-module="bgtsforms" ng-controller="SearchController as searchCtrl" data-toggle="validator" method="GET" id="search_mini_form" name="searchForm" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" role="form" novalidate>
    <div class="form-group">
		<p class="input-group">
			<input ng-model="searchCtrl.q" ng-class="{'border-red':searchForm.q.$invalid && searchForm.$submitted}" id="search" type="text" name="q" placeholder="Search Store..." class="form-control input-sm" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" required/>
			<span class="input-group-btn">
				<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Search')) ?>" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-search"></span></button>
			</span>
		</p>
    </div>
</form>
