<nav class="navbar navbar-default">
	<div class="container-fluid">
	  <div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topLinks" aria-expanded="false" aria-controls="navbar">
		  <span class="sr-only">Toggle navigation</span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		</button>
		<a class="navbar-logo" href="<?php echo $this->getUrl('') ?>" alt="<?php echo $this->getLogoAlt() ?>" title="<?php echo $this->getLogoAlt() ?>">
			<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
		</a>
	  </div>
	  <div id="topLinks" class="navbar-collapse collapse">
		<?php echo $this->getChildHtml('topLinks') ?>
		<ul class="nav navbar-nav navbar-right">
			<li>
				<?php echo $this->getChildHtml('topSearch') ?>
			</li>
		</ul>
	  </div>
	</div>
</nav>
