<div class="nopadding row col-md-12">
    <div class="nopadding row col-md-12">
        <?php echo $this->getChildHtml() ?>
        <?php /*p class="bugs"><?php echo $this->__('Help Us to Keep Magento Healthy') ?> - <a href="http://www.magentocommerce.com/bug-tracking" onclick="this.target='_blank'"><strong><?php echo $this->__('Report All Bugs') ?></strong></a> <?php echo $this->__('(ver. %s)', Mage::getVersion()) ?></p>
        <address><?php echo $this->getCopyright() ?></address*/ ?> 
    </div>
</div>
 