<div class="header-container">
    <div class="header">
        <div class="quick-access">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>
        <?php echo $this->getChildHtml('topContainer'); ?>
    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
<nav class="navbar navbar-default">
	<div class="container-fluid">
	  <div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topLinks" aria-expanded="false" aria-controls="navbar">
		  <span class="sr-only">Toggle navigation</span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="<?php echo $this->getUrl('') ?>" alt="<?php echo $this->getLogoAlt() ?>" title="<?php echo $this->getLogoAlt() ?>">
			<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
		</a>
	  </div>
	  <div id="topLinks" class="navbar-collapse collapse">
		<?php echo $this->getChildHtml('topLinks') ?> gago tong line na to
		<ul class="nav navbar-nav navbar-right">
			<li>
				<p class="welcome-msg">
					<?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?>
				</p>
			</li>
			<li>
				<?php echo $this->getChildHtml('topSearch') ?>
			</li>
		</ul>
	  </div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
</nav>
